title: dfmdmx
author: dfmd
email: daniel@dfmd.mx
description: > # this means to ignore newlines until "show_excerpts:"
  Professional board aimed to find practical applications for
  computed assisted form finding and automated machine manufacturing.

title: Daniel Fernandez Marmissolle-Daguerre
email: daniel@dfmd.mx
description: Portfolio of Daniel Fernandez Marmissolle-Daguerre, computational designer and architect.
url: https://www.dfmd.mx
baseurl: ""
#Used for post like structures
